import { readFileSync } from 'node:fs';
import { and, eq } from 'drizzle-orm';
import { DbService } from '../common/infra/db/db.service';
import { AuditService } from '../common/audit/audit.service';
import { assistantTemplates, ASSISTANT_SCHEMA_VERSION } from '../modules/assistants/schema';
import { validateAssistantPayload, rejectUnknownPayloadKeys } from '../modules/assistants/validation';
import { canonicalHash } from '../common/crypto/canonical-hash';

/**
 * Registry sync release job — TPL-1.2 (implementation; entry shim in
 * ./sync-template-registry.ts loads .env before this module imports).
 *
 * Upserts `assistant_templates` rows from the CI-published registry.json
 * (generated by products/agent-studio's generate-template-registry.mjs).
 * Runs ONCE per release, never per-replica, never as a migration — a
 * template version bump requires zero DDL.
 *
 * Safety (all fail-loud, nothing half-written):
 *  - entry hash MUST equal canonicalHash(entry.definition) — tampered or
 *    hand-edited registry content is refused before any write;
 *  - entry definition MUST pass validateAssistantPayload — uninstallable
 *    templates never reach the registry table;
 *  - entry min_engine_schema MUST be servable by this engine;
 *  - same slug@version with a DIFFERENT hash is refused outright (releases
 *    are immutable — bump the template version instead of rewriting);
 *  - same slug@version with the SAME hash is a no-op (idempotent reruns).
 *
 * Usage:
 *   pnpm templates:sync -- --file <registry.json> [--dry-run]
 *   DATABASE_URL=... pnpm templates:sync -- --file registry.json
 */

interface RegistryEntry {
  slug: string;
  version: string;
  hash: string;
  status: string;
  family: string;
  min_engine_schema: number;
  definition: unknown;
  bindings: unknown;
  eval_ref: unknown;
  release_policy: unknown;
}

function usageError(message: string): never {
  console.error(`sync-template-registry: ${message}`);
  console.error('usage: pnpm templates:sync -- --file <registry.json> [--dry-run]');
  process.exit(2);
}

export async function run(): Promise<void> {
  const argv = process.argv.slice(2);
  const fileFlag = argv.indexOf('--file');
  if (fileFlag === -1 || !argv[fileFlag + 1]) {
    usageError('--file <registry.json> is required');
  }
  const dryRun = argv.includes('--dry-run');
  const file = argv[fileFlag + 1];

  let envelope: { version?: number; templates?: RegistryEntry[] };
  try {
    envelope = JSON.parse(readFileSync(file, 'utf8')) as typeof envelope;
  } catch (err) {
    usageError(`cannot read registry file ${file} (${(err as Error).message})`);
  }
  if (envelope.version !== 1 || !Array.isArray(envelope.templates)) {
    usageError('registry envelope must be { version: 1, templates: [...] }');
  }
  const entries = envelope.templates as RegistryEntry[];

  // Validate everything BEFORE touching the database — a bad entry fails
  // the release without a partial sync.
  for (const entry of entries) {
    assertEntryShape(entry);
    const recomputed = canonicalHash(entry.definition);
    if (recomputed !== entry.hash) {
      throw new Error(`refusing ${entry.slug}@${entry.version}: registry hash mismatch (file says ${entry.hash}, recomputed ${recomputed})`);
    }
    // Unknown keys at ANY depth are an authoring defect (template-only
    // extensions leak) — refuse here too: the registry must only ever hold
    // payloads the install path accepts verbatim.
    try {
      rejectUnknownPayloadKeys(entry.definition as Record<string, unknown>);
    } catch (err) {
      throw new Error(`refusing ${entry.slug}@${entry.version}: ${(err as Error).message}`);
    }
    const validated = validateAssistantPayload(entry.definition);
    if (!validated.ok) {
      throw new Error(`refusing ${entry.slug}@${entry.version}: definition fails Engine validation`);
    }
    if (entry.min_engine_schema > ASSISTANT_SCHEMA_VERSION) {
      throw new Error(
        `refusing ${entry.slug}@${entry.version}: requires engine schema ${entry.min_engine_schema}, this engine serves ${ASSISTANT_SCHEMA_VERSION}`,
      );
    }
  }

  if (dryRun) {
    // Offline-safe: entry shape + hash + payload validation only, no database.
    for (const entry of entries) {
      console.log(`[dry-run] valid ${entry.slug}@${entry.version} (${entry.status}, schema ${entry.min_engine_schema})`);
    }
    console.log(`template registry dry run complete: ${entries.length} valid entries, 0 writes`);
    return;
  }

  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL is required — refusing to sync against a guessed database');
  }
  const db = new DbService();
  const audit = new AuditService(db);
  try {
    let inserted = 0;
    let unchanged = 0;
    for (const entry of entries) {
      const existing = await db.root
        .select({ hash: assistantTemplates.hash })
        .from(assistantTemplates)
        .where(and(eq(assistantTemplates.slug, entry.slug), eq(assistantTemplates.version, entry.version)))
        .limit(1);
      if (existing.length > 0) {
        if (existing[0].hash !== entry.hash) {
          throw new Error(
            `refusing ${entry.slug}@${entry.version}: hash differs from the synced row (releases are immutable — bump the template version instead)`,
          );
        }
        unchanged += 1;
        continue;
      }
      await db.root.insert(assistantTemplates).values({
        slug: entry.slug,
        version: entry.version,
        status: entry.status,
        family: entry.family,
        definition: entry.definition as Record<string, unknown>,
        bindings: (entry.bindings ?? {}) as Record<string, unknown>,
        evalRef: (entry.eval_ref ?? null) as Record<string, unknown> | null,
        releasePolicy: entry.release_policy as Record<string, unknown>,
        hash: entry.hash,
        minEngineSchema: entry.min_engine_schema,
      });
      await audit.add({
        action: 'template.registry_synced',
        resourceType: 'assistant_template',
        resourceId: `${entry.slug}@${entry.version}`,
        actorType: 'service',
        actorId: 'release-job',
        tenantId: null,
        details: { slug: entry.slug, version: entry.version, hash: entry.hash.slice(0, 16) },
      });
      inserted += 1;
    }
    console.log(`template registry sync complete: inserted=${inserted} unchanged=${unchanged}`);
  } finally {
    await db.onModuleDestroy();
  }
}

function assertEntryShape(entry: RegistryEntry): void {
  const problems: string[] = [];
  if (typeof entry.slug !== 'string' || entry.slug.length === 0) problems.push('slug');
  if (typeof entry.version !== 'string' || entry.version.length === 0) problems.push('version');
  if (typeof entry.hash !== 'string' || entry.hash.length !== 64) problems.push('hash (64 hex chars)');
  if (typeof entry.status !== 'string' || entry.status.length === 0) problems.push('status');
  if (typeof entry.family !== 'string' || entry.family.length === 0) problems.push('family');
  if (!Number.isInteger(entry.min_engine_schema)) problems.push('min_engine_schema');
  if (!entry.definition || typeof entry.definition !== 'object') problems.push('definition');
  if (!entry.release_policy || typeof entry.release_policy !== 'object') problems.push('release_policy');
  if (problems.length > 0) {
    throw new Error(`refusing registry entry: invalid fields (${problems.join(', ')})`);
  }
}
