/**
 * Contract composition (C-2', correction C7): ONE composed spec is the
 * entire public surface. Inputs:
 *
 *   - the runtime's pinned spec (Python export — unchanged, authoritative
 *     for its paths)
 *   - the engine's swagger export (scripts/export-openapi.ts)
 *   - the product manifests (products_manifests/*.yaml — the ownership map)
 *
 * Rules enforced here (CI fails on violation):
 *   1. Every path gets x-neryva-owner: platform | <product key>.
 *   2. Engine paths under a product's console.base_route or its
 *      runtime_routes belong to that product; everything else is platform.
 *   3. Runtime-spec paths map to the satellite owner via each manifest's
 *      satellite_runtime_routes prefixes (default: agent_studio).
 *   4. Path collisions between the two sources are errors unless identical.
 *   5. Bijection: every ga-stage manifest's declared routes must appear in
 *      the composed contract; building-stage manifests only warn.
 *
 * Usage:
 *   npx tsx scripts/compose-contract.ts \
 *     --runtime ../contracts/openapi/openapi.v1.json \
 *     --engine var/engine-openapi.json \
 *     --out ../contracts/openapi/openapi.composed.v1.json
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';

interface Args {
  runtime: string;
  engine: string;
  out: string;
}
interface Manifest {
  key: string;
  stage: 'registered' | 'building' | 'shadow' | 'ga' | 'deprecated';
  console?: { base_route: string };
  runtime_routes: string[];
  satellite_runtime_routes: string[];
}

function parseArgs(argv: string[]): Args {
  const get = (flag: string, fallback: string): string => {
    const i = argv.indexOf(flag);
    return i >= 0 && argv[i + 1] ? argv[i + 1] : fallback;
  };
  return {
    runtime: get('--runtime', join(process.cwd(), '..', 'contracts', 'openapi', 'openapi.v1.json')),
    engine: get('--engine', join(process.cwd(), 'var', 'engine-openapi.json')),
    out: get('--out', join(process.cwd(), '..', 'contracts', 'openapi', 'openapi.composed.v1.json')),
  };
}

function loadManifests(dir: string): Manifest[] {
  return readdirSync(dir)
    .filter((f: string) => f.endsWith('.yaml') || f.endsWith('.yml'))
    .map((f: string) => parse(readFileSync(join(dir, f), 'utf8')) as Manifest);
}

function prefixMatches(prefix: string, path: string): boolean {
  const norm = prefix.replace(/\/\*+$/, '').replace(/\/$/, '');
  return path === norm || path.startsWith(`${norm}/`);
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  for (const input of [args.runtime, args.engine]) {
    if (!existsSync(input)) {
      console.error(`missing input: ${input}`);
      process.exit(1);
    }
  }
  const manifestsDir = join(process.cwd(), 'products_manifests');
  const manifests = loadManifests(manifestsDir);
  const runtimeSpec = JSON.parse(readFileSync(args.runtime, 'utf8')) as { paths: Record<string, unknown>; info?: unknown };
  const engineSpec = JSON.parse(readFileSync(args.engine, 'utf8')) as { paths: Record<string, unknown>; info?: unknown };

  const composed: Record<string, unknown> = {
    openapi: '3.0.3',
    info: {
      title: 'Neryva Platform — Composed Contract',
      version: '1.0.0',
      description: 'Single source of truth for the entire public surface: engine (platform + product control plane) merged with the agent-runtime satellite contract. Every path carries x-neryva-owner. Generated by scripts/compose-contract.ts — never hand-edited.',
    },
    paths: {},
  };

  const errors: string[] = [];
  const warnings: string[] = [];
  const composedPaths = composed.paths as Record<string, Record<string, unknown>>;

  function ownerForEnginePath(path: string): string | null {
    for (const m of manifests) {
      if (m.console?.base_route && prefixMatches(m.console.base_route, path)) {
        return m.key;
      }
      if (m.runtime_routes.some((p) => prefixMatches(p, path))) {
        return m.key;
      }
    }
    return null; // platform
  }

  function ownerForRuntimePath(path: string): string {
    for (const m of manifests) {
      if (m.satellite_runtime_routes.some((p) => prefixMatches(p, path))) {
        return m.key;
      }
    }
    return 'agent_studio'; // today's only satellite — explicit default, no silent platform capture
  }

  function mergePaths(spec: { paths: Record<string, unknown> }, source: 'engine' | 'runtime'): void {
    for (const [path, item] of Object.entries(spec.paths ?? {})) {
      if (composedPaths[path]) {
        errors.push(`path collision between engine and runtime specs: ${path}`);
        continue;
      }
      const owner = source === 'engine' ? (ownerForEnginePath(path) ?? 'platform') : ownerForRuntimePath(path);
      const annotated = JSON.parse(JSON.stringify(item)) as Record<string, unknown>;
      annotated['x-neryva-owner'] = owner;
      if (source === 'runtime') {
        annotated['x-neryva-served-by'] = 'agent-runtime';
      }
      composedPaths[path] = annotated;
    }
  }

  mergePaths(engineSpec, 'engine');
  mergePaths(runtimeSpec, 'runtime');

  // Bijection: ga manifests' declared routes must exist in the composed spec.
  for (const m of manifests) {
    if (m.stage === 'deprecated') {
      continue;
    }
    const declared = [...(m.console?.base_route ? [m.console.base_route] : []), ...m.runtime_routes];
    for (const route of declared) {
      const present = Object.keys(composedPaths).some((p) => prefixMatches(route, p));
      if (!present) {
        if (m.stage === 'ga') {
          errors.push(`manifest ${m.key} (stage=ga) declares route ${route} missing from the composed contract`);
        } else {
          warnings.push(`manifest ${m.key} (stage=${m.stage}) declares route ${route} not yet in the contract`);
        }
      }
    }
  }

  // No unowned paths: engine paths are platform-or-product by construction;
  // assert runtime paths never leaked into a product console prefix.
  for (const [path, item] of Object.entries(composedPaths)) {
    const owner = item['x-neryva-owner'] as string | undefined;
    if (!owner) {
      errors.push(`unowned path: ${path}`);
    }
  }

  writeFileSync(args.out, JSON.stringify(composed, null, 2));
  const count = Object.keys(composedPaths).length;
  // eslint-disable-next-line no-console
  console.log(`composed contract written: ${args.out} (${count} paths; ${warnings.length} warnings)`);
  for (const w of warnings) {
    // eslint-disable-next-line no-console
    console.warn(`  warn: ${w}`);
  }
  if (errors.length > 0) {
    for (const e of errors) {
      // eslint-disable-next-line no-console
      console.error(`  ERROR: ${e}`);
    }
    process.exit(1);
  }
}

main();
